export const APP_LOAD_REQUEST = "APP_LOAD_REQUEST";
export const APP_LOAD_SUCCESS = "APP_LOAD_SUCCESS";

export const APP_SET_ERROR = "APP_SET_ERROR";

export const APP_LOAD_SETTINGS_SUCCESS = "APP_LOAD_SETTINGS_SUCCESS";

export const APP_CHANGE_LANGUAGE_REQUEST = "APP_CHANGE_LANGUAGE_REQUEST";
export const APP_CHANGE_LANGUAGE_SUCCESS = "APP_CHANGE_LANGUAGE_SUCCESS";
export const APP_CHANGE_LANGUAGE_ERROR = "APP_CHANGE_LANGUAGE_ERROR";

export const APP_LOAD_SCHEMA_REQUEST = "APP_LOAD_SCHEMA_REQUEST";
export const APP_LOAD_SCHEMA_SUCCESS = "APP_LOAD_SCHEMA_SUCCESS";
export const APP_LOAD_SCHEMA_ERROR = "APP_LOAD_SCHEMA_ERROR";

export const APP_SET_DATA = "APP_SET_DATA";
export const APP_REMOVE_DATA = "APP_REMOVE_DATA";
export const APP_SET_ACTION_RESULT = "APP_SET_ACTION_RESULT";